@startuml
'https://plantuml.com/sequence-diagram

class HTMLGenerator {
 # String[] siteInfo
 # boolean[] folders
 # static final String START

 + HTMLGenerator (String webName, String author, String javaChoice, String cssChoice)
 - boolean checkForYes (String input)
 # void generateSiteData()
 # void writeToSite()
 - void generateDirectory(boolean isFolder, String folderName)
 # void manageDirectoryGeneration()
}

class Solution43{
+ public static void main(String[] args)
}

HTMLGenerator -- Solution43

@enduml