@startuml
'https://plantuml.com/class-diagram

class NamesSort{
- names : TreeMap <String, String>
- numberOfNames : Integer
__
- int CountNumberOfNames(String fileName)
- void placeNamesInMap(String fileName)
+ void scanNames(String fileName)
+ void printNames()
}

class Solution41{
fileName : String

}
@enduml